// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvrGlOG63lm99NiDApC0N80jn61PpOG8o',
    appId: '1:1030242914710:web:1394bba49fdbe2e9ddcdb7',
    messagingSenderId: '1030242914710',
    projectId: 'simple-todo-beran',
    authDomain: 'simple-todo-beran.firebaseapp.com',
    storageBucket: 'simple-todo-beran.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAePokZH7BD60cOTsS2EvHzQYoJBx2vTFo',
    appId: '1:1030242914710:android:a0294a31ad2d8ea7ddcdb7',
    messagingSenderId: '1030242914710',
    projectId: 'simple-todo-beran',
    storageBucket: 'simple-todo-beran.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKNpe5ZhMebaMfijfxHc4G7e8Ku1XwMA4',
    appId: '1:1030242914710:ios:c42bab1d41e56d15ddcdb7',
    messagingSenderId: '1030242914710',
    projectId: 'simple-todo-beran',
    storageBucket: 'simple-todo-beran.appspot.com',
    iosClientId: '1030242914710-tsdm2c2tjuk4dmuv330qb9ds4nn6a7cr.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
